package:
    name: pycwr
    version: 0.3.7

build:
    skip: True # [py<35]

source:
    git_url: https://github.com/YvZheng/pycwr.git

requirements:
    build:
       - python
       - setuptools
    host:
       - python
       - setuptools

    run:
        - 'python>=3.8'
        - 'numpy'
        - 'scipy'
        - 'matplotlib'
        - 'netcdf4'
        - 'cartopy'
        - 'pandas'
        - 'easydict'
        - 'pyproj'
        - 'xarray'
        - 'pyqt>=5.8'

about:
    home: https://github.com/YvZheng/pycwr
    description: 
    license: MIT
    license_file: LICENSE.txt
